config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items, only:[:create, :destroy]
  resources :carts, only:[:show]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
    belongs_to :product
    belongs_to :cart
    validates :qty,:product_id,:cart_id,presence: true
    validates :qty, numericality: {only_integer: true, greater_than: 0}
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :cart_items, dependent: :destroy
    validates :name,:price, presence: true
    validates :price, numericality: {only_integer: true, greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find(session[:cart_id])
      else
        cart = Cart.create
        session[:cart_id] = cart.id
      end
      cart
    end
    helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

    def create
        @cart_item = CartItem.new(qty: params[:qty], product_id: params[:product_id], cart_id: session[:cart_id])
        if @cart_item.save
            redirect_to root_path
        else
            render "products/index"
        end
    end
    def destroy
        cart_item = CartItem.find(params[:id])
        cart_item.destroy
        redirect_to root_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = Cart.find(params[:id])
        @cart_items = CartItem.where(cart_id: session[:cart_id])
        @sum = 0
        @cart_items.each do |c|
            @sum += c.product.price*c.product.qty
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        name = params[:product][:name]
        price = params[:product][:price]
        @product = Product.new(name: name, price: price)
        if @product.save
            redirect_to products_path
        else
            render 'new'
        end
    end

    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to products_path
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        current_cart
        render 'main'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>カートの中身</h1></br>
<p>これはid<%= @cart[:id] %>のカートです</p>
<% @cart_items.each do |c| %>
  <%= c.product.name %>
  <%= c.product.price %>円
  <%= c.qty %>個</br>
  <%= button_to 'カートから削除', cart_item_path(c.id), method: :delete,data: { confirm: '本当に削除しますか?' } %></br>
<% end %>
合計金額:<%= @sum %>円</br>
<%= link_to '[topへ戻る]', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>L6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<%= link_to '[TOPへ戻る]', root_path %></br>
<%= link_to '新規追加', new_product_path %></br>

<% @products.each do |p| %>
  <%= p.name %>
  <%= p.price %>円
  <%= link_to '商品を削除', product_path(p.id), mesthod: :delete %></br>
  <%= form_tag cart_items_path(product_id: p.id), method: :post do %>
    <%= label_tag :qty, '数量' %>
    <%= number_field_tag :qty, 1,min:1 %>
    <%= submit_tag 'カートに追加' %>
    </br>
   <% end %>
 <% end%>

app/views/products/new.html.erb
<h1>新規商品登録</h1>
<% if @product.errors.present? %>
<h3>エラーがあります</h3>
<ul>
  <% @product.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @product, url: {action: :create} do |f| %>
  <%= f.label :name,'商品名' %>
  <%= f.text_field :name %>
  <%= f.label :price,'価格' %>
  <%= f.text_field :price %>円
  <%= f.submit '登録' %>
<% end %>

<%= link_to '[TOPへ戻る]', root_path %></br>

app/views/top/main.html.erb
<h1>ようこそ</h1>
<p><%= link_to '商品一覧', products_path %></p>
<p><%= link_to 'カート', cart_path(session[:cart_id]) %></p>